Repository yilmazvolkan/purposefulCommunityPlatform, pull requests merged in 2019-11, with the labels that each got.

#6 Initilization
  purposeful-community-cloud/pom.xml
  purposeful-community-cloud/src/main/java/com/evteam/purposefulcommunitycloud/configuration/CorsConfig.java
  purposeful-community-cloud/src/main/java/com/evteam/purposefulcommunitycloud/configuration/SwaggerConfig.java
  purposeful-community-cloud/src/main/java/com/evteam/purposefulcommunitycloud/constant/ConfigConstants.java
Labels: Backend, Effort: Medium, Priority: High, Status: Done

#7 Backend security initilization
  purposeful-community-cloud/src/main/java/com/evteam/purposefulcommunitycloud/constant/ErrorConstants.java
  purposeful-community-cloud/src/main/java/com/evteam/purposefulcommunitycloud/security/JwtGenerator.java
  purposeful-community-cloud/src/main/java/com/evteam/purposefulcommunitycloud/security/JwtResolver.java
  purposeful-community-cloud/src/main/resources/application.properties
Labels: Backend, Effort: Medium, Priority: High, Status: Done, enhancement

#8 Backend user initilization
  purposeful-community-cloud/pom.xml
  purposeful-community-cloud/src/main/java/com/evteam/purposefulcommunitycloud/common/AbstractEntity.java
  purposeful-community-cloud/src/main/java/com/evteam/purposefulcommunitycloud/common/AuditingEntityListener.java
  purposeful-community-cloud/src/main/java/com/evteam/purposefulcommunitycloud/common/Converter.java
  purposeful-community-cloud/src/main/java/com/evteam/purposefulcommunitycloud/configuration/SwaggerConfig.java
  purposeful-community-cloud/src/main/java/com/evteam/purposefulcommunitycloud/constant/GeneralConstants.java
  purposeful-community-cloud/src/main/java/com/evteam/purposefulcommunitycloud/controller/UserController.java
  purposeful-community-cloud/src/main/java/com/evteam/purposefulcommunitycloud/mapper/RegisterMapper.java
  purposeful-community-cloud/src/main/java/com/evteam/purposefulcommunitycloud/model/dto/LoginDto.java
  purposeful-community-cloud/src/main/java/com/evteam/purposefulcommunitycloud/model/dto/RegisterDto.java
  purposeful-community-cloud/src/main/java/com/evteam/purposefulcommunitycloud/model/entity/User.java
  purposeful-community-cloud/src/main/java/com/evteam/purposefulcommunitycloud/model/resource/LoginResource.java
  purposeful-community-cloud/src/main/java/com/evteam/purposefulcommunitycloud/model/resource/UserResource.java
  purposeful-community-cloud/src/main/java/com/evteam/purposefulcommunitycloud/repository/UserRepository.java
  purposeful-community-cloud/src/main/java/com/evteam/purposefulcommunitycloud/service/UserService.java
Labels: Backend, Effort: Medium, Priority: High, Status: Done, enhancement

#9 Configuration Problems Bug Fix
  purposeful-community-cloud/pom.xml
  purposeful-community-cloud/src/main/java/com/evteam/purposefulcommunitycloud/mapper/RegisterMapper.java
  purposeful-community-cloud/src/main/java/com/evteam/purposefulcommunitycloud/model/dto/LoginDto.java
  purposeful-community-cloud/src/main/java/com/evteam/purposefulcommunitycloud/model/dto/RegisterDto.java
  purposeful-community-cloud/src/main/java/com/evteam/purposefulcommunitycloud/model/entity/User.java
  purposeful-community-cloud/src/main/java/com/evteam/purposefulcommunitycloud/model/resource/UserResource.java
  purposeful-community-cloud/src/main/java/com/evteam/purposefulcommunitycloud/service/UserService.java
  purposeful-community-cloud/src/main/resources/application.properties
Labels: Backend, Effort: Medium, Priority: High, Status: Done, bug

#10 Login mechanism is injected
  purposeful-community-cloud/src/main/java/com/evteam/purposefulcommunitycloud/controller/UserController.java
  purposeful-community-cloud/src/main/java/com/evteam/purposefulcommunitycloud/mapper/LoginMapper.java
  purposeful-community-cloud/src/main/java/com/evteam/purposefulcommunitycloud/model/dto/LoginDto.java
  purposeful-community-cloud/src/main/java/com/evteam/purposefulcommunitycloud/model/dto/RegisterDto.java
  purposeful-community-cloud/src/main/java/com/evteam/purposefulcommunitycloud/model/entity/User.java
  purposeful-community-cloud/src/main/java/com/evteam/purposefulcommunitycloud/model/resource/LoginResource.java
  purposeful-community-cloud/src/main/java/com/evteam/purposefulcommunitycloud/repository/UserRepository.java
  purposeful-community-cloud/src/main/java/com/evteam/purposefulcommunitycloud/service/UserService.java
Labels: Backend, Effort: Low, Priority: Medium, Status: Done, enhancement

#13 Initialize mobile
  PurposefulCommunity/.gitignore
  PurposefulCommunity/.idea/.name
  PurposefulCommunity/.idea/codeStyles/Project.xml
  PurposefulCommunity/.idea/codeStyles/codeStyleConfig.xml
  PurposefulCommunity/.idea/dictionaries/volkanyilmaz.xml
  PurposefulCommunity/.idea/gradle.xml
  PurposefulCommunity/.idea/misc.xml
  PurposefulCommunity/.idea/runConfigurations.xml
  PurposefulCommunity/.idea/vcs.xml
  PurposefulCommunity/app/.gitignore
  PurposefulCommunity/app/build.gradle
  PurposefulCommunity/app/proguard-rules.pro
  PurposefulCommunity/app/src/androidTest/java/com/bounswe/purposefulcommunity/ExampleInstrumentedTest.kt
  PurposefulCommunity/app/src/main/AndroidManifest.xml
  PurposefulCommunity/app/src/main/java/com/bounswe/purposefulcommunity/Fragments/LoginActivity.kt
  PurposefulCommunity/app/src/main/java/com/bounswe/purposefulcommunity/Fragments/MainActivity.kt
  PurposefulCommunity/app/src/main/java/com/bounswe/purposefulcommunity/Fragments/RegisterActivity.kt
  PurposefulCommunity/app/src/main/res/anim/slide_in_left.xml
  PurposefulCommunity/app/src/main/res/anim/slide_in_right.xml
  PurposefulCommunity/app/src/main/res/anim/slide_out_left.xml
  PurposefulCommunity/app/src/main/res/anim/slide_out_right.xml
  PurposefulCommunity/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  PurposefulCommunity/app/src/main/res/drawable/ic_launcher_background.xml
  PurposefulCommunity/app/src/main/res/drawable/web_hi_res_512.png
  PurposefulCommunity/app/src/main/res/layout/activity_login.xml
  PurposefulCommunity/app/src/main/res/layout/activity_main.xml
  PurposefulCommunity/app/src/main/res/layout/activity_register.xml
  PurposefulCommunity/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  PurposefulCommunity/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  PurposefulCommunity/app/src/main/res/mipmap-hdpi/ic_launcher.png
  PurposefulCommunity/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  PurposefulCommunity/app/src/main/res/mipmap-mdpi/ic_launcher.png
  PurposefulCommunity/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  PurposefulCommunity/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  PurposefulCommunity/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  PurposefulCommunity/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  PurposefulCommunity/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  PurposefulCommunity/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  PurposefulCommunity/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  PurposefulCommunity/app/src/main/res/values/colors.xml
  PurposefulCommunity/app/src/main/res/values/dimens.xml
  PurposefulCommunity/app/src/main/res/values/strings.xml
  PurposefulCommunity/app/src/main/res/values/styles.xml
  PurposefulCommunity/app/src/test/java/com/bounswe/purposefulcommunity/ExampleUnitTest.kt
  PurposefulCommunity/build.gradle
  PurposefulCommunity/gradle.properties
  PurposefulCommunity/gradle/wrapper/gradle-wrapper.jar
  PurposefulCommunity/gradle/wrapper/gradle-wrapper.properties
  PurposefulCommunity/gradlew
  PurposefulCommunity/gradlew.bat
  PurposefulCommunity/settings.gradle
Labels: Mobile

#16 Remote DB Configurations are done
  purposeful-community-cloud/src/main/java/com/evteam/purposefulcommunitycloud/constant/ConfigConstants.java
  purposeful-community-cloud/src/main/java/com/evteam/purposefulcommunitycloud/service/UserService.java
  purposeful-community-cloud/src/main/resources/application.properties
Labels: Backend, Effort: Low, Status: Done, enhancement

#17 student id and phone is removed
  purposeful-community-cloud/src/main/java/com/evteam/purposefulcommunitycloud/model/dto/RegisterDto.java
  purposeful-community-cloud/src/main/java/com/evteam/purposefulcommunitycloud/model/entity/User.java
  purposeful-community-cloud/src/main/java/com/evteam/purposefulcommunitycloud/model/resource/UserResource.java
Labels: Backend, Effort: Low, bug

#18 Backend community specific data type creation
  purposeful-community-cloud/pom.xml
  purposeful-community-cloud/src/main/java/com/evteam/purposefulcommunitycloud/constant/FieldType.java
  purposeful-community-cloud/src/main/java/com/evteam/purposefulcommunitycloud/controller/CSDataController.java
  purposeful-community-cloud/src/main/java/com/evteam/purposefulcommunitycloud/controller/CommunityController.java
  purposeful-community-cloud/src/main/java/com/evteam/purposefulcommunitycloud/mapper/CommunityMapper.java
  purposeful-community-cloud/src/main/java/com/evteam/purposefulcommunitycloud/mapper/DataFieldMapper.java
  purposeful-community-cloud/src/main/java/com/evteam/purposefulcommunitycloud/mapper/DataTemplateMapper.java
  purposeful-community-cloud/src/main/java/com/evteam/purposefulcommunitycloud/model/dto/CommunityDto.java
  purposeful-community-cloud/src/main/java/com/evteam/purposefulcommunitycloud/model/dto/DataFieldDto.java
  purposeful-community-cloud/src/main/java/com/evteam/purposefulcommunitycloud/model/dto/DataTemplateDto.java
  purposeful-community-cloud/src/main/java/com/evteam/purposefulcommunitycloud/model/entity/Community.java
  purposeful-community-cloud/src/main/java/com/evteam/purposefulcommunitycloud/model/entity/DataField.java
  purposeful-community-cloud/src/main/java/com/evteam/purposefulcommunitycloud/model/entity/DataTemplate.java
  purposeful-community-cloud/src/main/java/com/evteam/purposefulcommunitycloud/model/resource/CommunityResource.java
  purposeful-community-cloud/src/main/java/com/evteam/purposefulcommunitycloud/model/resource/DataFieldResource.java
  purposeful-community-cloud/src/main/java/com/evteam/purposefulcommunitycloud/model/resource/DataTemplateResource.java
  purposeful-community-cloud/src/main/java/com/evteam/purposefulcommunitycloud/repository/CommunityRepository.java
  purposeful-community-cloud/src/main/java/com/evteam/purposefulcommunitycloud/repository/DataFieldRepository.java
  purposeful-community-cloud/src/main/java/com/evteam/purposefulcommunitycloud/repository/DataTemplateRepository.java
  purposeful-community-cloud/src/main/java/com/evteam/purposefulcommunitycloud/repository/UserRepository.java
  purposeful-community-cloud/src/main/java/com/evteam/purposefulcommunitycloud/service/CSDataService.java
  purposeful-community-cloud/src/main/java/com/evteam/purposefulcommunitycloud/service/CommunityService.java
Labels: Backend, Effort: High, Priority: Medium, Status: Done, enhancement

#20 Sign in and sign up functionality is added
  PurposefulCommunity/app/build.gradle
  PurposefulCommunity/app/src/main/AndroidManifest.xml
  PurposefulCommunity/app/src/main/java/com/bounswe/purposefulcommunity/API/RetrofitClient.kt
  PurposefulCommunity/app/src/main/java/com/bounswe/purposefulcommunity/Fragments/CommunityActivity.kt
  PurposefulCommunity/app/src/main/java/com/bounswe/purposefulcommunity/Fragments/LoginActivity.kt
  PurposefulCommunity/app/src/main/java/com/bounswe/purposefulcommunity/Fragments/RegisterActivity.kt
  PurposefulCommunity/app/src/main/java/com/bounswe/purposefulcommunity/Models/SignInBody.kt
  PurposefulCommunity/app/src/main/java/com/bounswe/purposefulcommunity/Models/SignInRes.kt
  PurposefulCommunity/app/src/main/java/com/bounswe/purposefulcommunity/Models/SignUpBody.kt
  PurposefulCommunity/app/src/main/res/drawable/ic_add_white_24dp.xml
  PurposefulCommunity/app/src/main/res/layout/activity_community.xml
  PurposefulCommunity/app/src/main/res/layout/activity_register.xml
  PurposefulCommunity/app/src/main/res/layout/content_community.xml
  PurposefulCommunity/app/src/main/res/values/strings.xml
Labels: Mobile

#22 Get All Communities end point is added
  purposeful-community-cloud/src/main/java/com/evteam/purposefulcommunitycloud/controller/CommunityController.java
  purposeful-community-cloud/src/main/java/com/evteam/purposefulcommunitycloud/mapper/CommunityMapper.java
  purposeful-community-cloud/src/main/java/com/evteam/purposefulcommunitycloud/service/CommunityService.java
Labels: Backend, Effort: Low, enhancement

#23 Community feed is created
  PurposefulCommunity/app/src/main/AndroidManifest.xml
  PurposefulCommunity/app/src/main/java/com/bounswe/purposefulcommunity/API/RetrofitClient.kt
  PurposefulCommunity/app/src/main/java/com/bounswe/purposefulcommunity/Adapters/CustomAdapter.kt
  PurposefulCommunity/app/src/main/java/com/bounswe/purposefulcommunity/Fragments/CommunityActivity.kt
  PurposefulCommunity/app/src/main/java/com/bounswe/purposefulcommunity/Fragments/LoginActivity.kt
  PurposefulCommunity/app/src/main/java/com/bounswe/purposefulcommunity/Fragments/RegisterActivity.kt
  PurposefulCommunity/app/src/main/java/com/bounswe/purposefulcommunity/Fragments/ShowCommActivity.kt
  PurposefulCommunity/app/src/main/java/com/bounswe/purposefulcommunity/Models/CommShowBody.kt
  PurposefulCommunity/app/src/main/java/com/bounswe/purposefulcommunity/Models/CommunityBody.kt
  PurposefulCommunity/app/src/main/java/com/bounswe/purposefulcommunity/Models/TokenBody.kt
  PurposefulCommunity/app/src/main/res/drawable/ic_arrow_forward.xml
  PurposefulCommunity/app/src/main/res/layout/activity_community.xml
  PurposefulCommunity/app/src/main/res/layout/activity_login.xml
  PurposefulCommunity/app/src/main/res/layout/activity_register.xml
  PurposefulCommunity/app/src/main/res/layout/activity_show_comm.xml
  PurposefulCommunity/app/src/main/res/layout/content_community.xml
  PurposefulCommunity/app/src/main/res/layout/item_layout.xml
  PurposefulCommunity/app/src/main/res/values/strings.xml
  PurposefulCommunity/app/src/main/res/values/styles.xml
Labels: Mobile

#25 Create community is implemented
  PurposefulCommunity/app/src/main/AndroidManifest.xml
  PurposefulCommunity/app/src/main/java/com/bounswe/purposefulcommunity/API/RetrofitClient.kt
  PurposefulCommunity/app/src/main/java/com/bounswe/purposefulcommunity/Fragments/CommunityActivity.kt
  PurposefulCommunity/app/src/main/java/com/bounswe/purposefulcommunity/Fragments/CreateCommActivity.kt
  PurposefulCommunity/app/src/main/java/com/bounswe/purposefulcommunity/Fragments/LoginActivity.kt
  PurposefulCommunity/app/src/main/java/com/bounswe/purposefulcommunity/Fragments/RegisterActivity.kt
  PurposefulCommunity/app/src/main/java/com/bounswe/purposefulcommunity/Models/CreateCommBody.kt
  PurposefulCommunity/app/src/main/res/layout/activity_create_comm.xml
  PurposefulCommunity/app/src/main/res/values/strings.xml
Labels: Mobile
